from aiogram.fsm.state import State, StatesGroup


class WithdrawSG(StatesGroup):
    amount = State()


class AdminSG(StatesGroup):
    set_value = State()
    wait_post = State()
    wait_buttons = State()
    wait_btn_color = State()
    wait_delay = State()
    wait_offer_chat = State()
    wait_campaign = State()
    wait_reject = State()
    wait_broadcast = State()
    wait_emojis = State()
    wait_user = State()
    wait_user_stars = State()
    wait_contest_text = State()
    wait_contest_photo = State()
    wait_contest_sponsors = State()
    wait_contest_button = State()
    wait_contest_channel = State()
    wait_contest_winners = State()
    wait_contest_end_value = State()
    wait_contest_own = State()
    wait_channel_add = State()
    wait_resource_add = State()
    wait_spam_post = State()
    wait_spam_buttons = State()
    wait_spam_timing = State()
    wait_greet_text = State()
    wait_greet_post = State()
    wait_greet_buttons = State()
    wait_greet_kd = State()
    wait_namer_names = State()
    wait_namer_interval = State()
    wait_combo_post = State()
    wait_combo_buttons = State()
    wait_combo_value = State()
    wait_combo_offset = State()
    wait_ub_phone = State()
    wait_ub_code = State()
    wait_ub_2fa = State()
    wait_ub_hello = State()
    wait_ub_gift = State()
    wait_ub_api_id = State()
    wait_ub_api_hash = State()
